### ISSUE TITLE
Links navigating to glossary instead of intended page

### ISSUE THREAD

**Issue by kmartens27** [Vandit1604/jenkins-docs#80] opened 2023-12-15 22:06 UTC
It appears that there are several links in the documentation that are intended to go to a specific page or section, but instead are going to either the top of the intended page (away from the section), the glossary entry for that term, or not navigating away from their original page.

Pages where I found this:

Running a Pipeline:
* https://vandit1604.github.io/jenkins-docs/user-docs/2.426.1/glossary/index.html#multibranch (leads to glossary page)
* https://vandit1604.github.io/jenkins-docs/user-docs/2.426.1/pipeline/jenkinsfile.html#handling-parameters (leads to Jekinsfile page, but not the parameters section as expected)

Branches and Pull Requests:
* https://vandit1604.github.io/jenkins-docs/user-docs/2.426.1/glossary/index.html#jenkinsfile (leads to glossary page)

Extending with Shared Libraries:
* https://vandit1604.github.io/jenkins-docs/user-docs/2.426.1/pipeline/shared-libraries.html#global-shared-libraries (does not navigate to intended section)
* https://vandit1604.github.io/jenkins-docs/user-docs/2.426.1/pipeline/shared-libraries.html#folder-level-shared-libraries

Pipeline Development Tools:
* https://vandit1604.github.io/jenkins-docs/user-docs/2.426.1/pipeline/getting-started.html#built-in-documentation (does not go to built-in documentation section as intended)
* https://vandit1604.github.io/jenkins-docs/user-docs/2.426.1/glossary/index.html#../managing/cli (goes to glossary)
* https://vandit1604.github.io/jenkins-docs/user-docs/2.426.1/glossary/index.html#shared-libraries (goes to glossary)

Pipeline Syntax:
* https://vandit1604.github.io/jenkins-docs/user-docs/2.426.1/pipeline/syntax.html (stays on page, instead of going to Pipeline index page)

Jenkins CLI:
* https://vandit1604.github.io/jenkins-docs/user-docs/2.426.1/managing/security.html#ssh-server (does not go to Security documentation)

In-process Script Approval:
* https://vandit1604.github.io/jenkins-docs/user-docs/2.426.1/glossary/index.html#script-console (goes to glossary instead of Script Console documentation)
* https://vandit1604.github.io/jenkins-docs/user-docs/2.426.1/glossary/index.html#pipeline (should go to Pipeline documentation instead of glossary)

Securing Jenkins:
* https://vandit1604.github.io/jenkins-docs/user-docs/2.426.1/security/index.html#dev-docs:security:access-control (does not navigate away from current page)
* https://vandit1604.github.io/jenkins-docs/user-docs/2.426.1/security/index.html#dev-docs:security:markup-formatter (does not navigate away from current page)

Reverse proxy configuration index:
* https://vandit1604.github.io/jenkins-docs/user-docs/2.426.1/system-administration/reverse-proxy-configuration-troubleshooting/ (does not actually lead to reverse proxy - issues page)

Is there something that was changed that could have lead to these links navigating incorrectly?

**Comment by Vandit1604** [comment] 2023-12-16 22:03
> * https://vandit1604.github.io/jenkins-docs/user-docs/2.426.1/glossary/index.html#multibranch (leads to glossary page) 
> * https://vandit1604.github.io/jenkins-docs/user-docs/2.426.1/glossary/index.html#jenkinsfile (leads to glossary page)
> * https://vandit1604.github.io/jenkins-docs/user-docs/2.426.1/glossary/index.html#script-console (goes to glossary instead of Script Console documentation)
This fragments don't exist in `glossary/index.adoc` 


> Is there something that was changed that could have lead to these links navigating incorrectly?

This links were angle brackets link before that may be the cause of the errors

Raised this PR #89

**Comment by Vandit1604** [comment] 2024-01-07 19:11
Closing as this is completed by #89

**Closed by Vandit1604** 2024-01-07 19:11 UTC
